version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn package
    - mv target/number-service-cicd-0.0.1.jar number-service-cicd-0.0.1.jar
    - echo Buid package completion
artifacts:
  files:
    - number-service-cicd-0.0.1.jar
    - .ebextensions/**/*


